Task 17.10
AlnurT/Skillbox_tasks pull request #19
Opened 2022-05-24 11:07 UTC by AlnurT

2022-06-21 13:37 UTC, E1-Bart0 requested changes

2022-06-21 18:26 UTC, E1-Bart0 commented on List comprehensions/task_17_10/task_17_10.py
> +    return cypher
Предложешь еще решение)?

2022-06-30 13:08 UTC, AlnurT commented on List comprehensions/task_17_10/task_17_10.py
> +    return cypher
Пробовал через replace и format, не получалось. Пробовал через список, знаки мешают и по сложности тоже самое выходит. Нужно полностью код поменять или что-то конкретное? Кроме получения элемента по номеру, ничего в голову не лезет.

2022-07-01 11:00 UTC, AlnurT commented on List comprehensions/task_17_10/task_17_10.py
> +    return cypher
Спасибо, действительно легко вышло)

2022-07-04 17:07 UTC, E1-Bart0 approved these changes

2022-07-04 17:07 UTC, E1-Bart0 commented on List comprehensions/task_17_10/task_17_10.py
> +    return text.translate(cypher)
У меня как-то так получилось. Можно использовать не maketrans, a просто словарь. Ну давай так оставим
```
def solution(data, shift):
    translater = {97 + i: 97 + (i + shift) % 26 for i in range(26)}
    return data.translate(translater)
```

2022-07-06 14:55 UTC, merged