Task 17.8
AlnurT/Skillbox_tasks pull request #31
Opened 2022-05-30 13:45 UTC by AlnurT

2022-06-21 19:00 UTC, E1-Bart0 requested changes

2022-06-30 13:36 UTC, E1-Bart0 requested changes

2022-06-30 13:36 UTC, E1-Bart0 commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
Все хорошо, но не по-питонячи
Какая есть функция позволяющая избежать использования здесь range

2022-06-30 13:36 UTC, E1-Bart0 commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
Чем отличается:
-  [_ for _ in range(5)]
- (_ for _ in range(5))
?

2022-06-30 13:41 UTC, E1-Bart0 commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
> (можно использовать range или больше меньше)
range я имел в виду использовать в качестве (0 <= x <= 1) == x in range(0, 2)

2022-07-01 09:47 UTC, AlnurT commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
> Все хорошо, но не по-питонячи Какая есть функция позволяющая избежать использования здесь range

enumerate

2022-07-01 09:48 UTC, AlnurT commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
> Чем отличается:
> 
> * [_ for _ in range(5)]
> * (_ for _ in range(5))
>   ?

2 меньше памяти ест, т.к. кортеж

2022-07-01 09:52 UTC, AlnurT commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
> > (можно использовать range или больше меньше)
> > range я имел в виду использовать в качестве (0 <= x <= 1) == x in range(0, 2)

Не знал, что в for так можно: (0 <= x <= 1)

2022-07-04 17:08 UTC, E1-Bart0 commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
Чем отличается:

[_ for _ in range(5)]
(_ for _ in range(5))
?
2 меньше памяти ест, т.к. кортеж

Нет, попробуй сделать print и посмотореть что будет? Это не кортеж

2022-07-04 17:09 UTC, E1-Bart0 requested changes

2022-07-04 17:09 UTC, E1-Bart0 commented on List comprehensions/task_17_8/task_17_8.py
> +        )
Можно убрать одни скобки и надо разобраться почему такое решение лучше чем с использованием []

2022-07-06 14:57 UTC, AlnurT commented on List comprehensions/task_17_8/task_17_8.py
> +        ]
Ааааа, это генератор, понял

2022-10-17 08:22 UTC, merged