Task 18.5
AlnurT/Skillbox_tasks pull request #32
Opened 2022-05-30 14:19 UTC by AlnurT

2022-06-22 13:14 UTC, E1-Bart0 requested changes

2022-06-22 13:14 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/task_18_5.py
> +            break
Сделаешь без if -else

2022-06-22 13:14 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/task_18_5.py
> +        return 3
Придумаешь как через list comprehensive сделать?

2022-07-04 17:21 UTC, E1-Bart0 requested changes

2022-07-04 17:21 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/task_18_5.py
> +    digit = tuple((symbol for symbol in password if symbol.isdigit()))
Лишние скобки

2022-07-04 17:21 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/task_18_5.py
> +    return 0
Давай попробуем рейзить свои собственные ошибки и ловить их через try: except
У тебя вроде норм получилось, можно было бы еще enum добавить и назвать функцию более понятно )

2022-07-04 17:21 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/test_task_18_2.py
> +    ],
а QWERTYUI должен быть принят или нет)?

2022-07-04 17:21 UTC, E1-Bart0 commented on Basic collections - string/task_18_5/task_18_5.py
> +    digit = tuple((symbol for symbol in password if symbol.isdigit()))
и тебе не обязательно делать так
Смотри:
sum(1 for symbol in password if symbol.isdigit()))
Здесь будет более оптимально, мы в память не загружаем тюпл, так как здесь используется генератор - мы идем до первой 1 потом складываем ее и идем дальше - в памяти храним только counter который суммирет

2022-08-17 12:57 UTC, AlnurT commented on Basic collections - string/task_18_5/test_task_18_2.py
> +    ],
Нет, ошибка о малом количестве цифр

2022-08-17 13:02 UTC, AlnurT commented on Basic collections - string/task_18_5/task_18_5.py
> +    return 0
try: except - это вместо ошибок выдавать желаемое?

2022-08-17 13:04 UTC, AlnurT commented on Basic collections - string/task_18_5/task_18_5.py
> +    return 0
Здесь нужно это делать?

2022-10-17 08:22 UTC, merged