Task 18.6
AlnurT/Skillbox_tasks pull request #33
Opened 2022-05-31 09:21 UTC by AlnurT

2022-06-22 13:20 UTC, E1-Bart0 requested changes

2022-06-22 13:20 UTC, E1-Bart0 commented on Basic collections - string/task_18_6/task_18_6.py
> +            )
А какже f-стринг?

2022-07-01 11:34 UTC, AlnurT commented on Basic collections - string/task_18_6/task_18_6.py
> +            )
просто тема была форматирование и я решил попробовать через format сделать

2022-07-04 17:25 UTC, E1-Bart0 requested changes

2022-07-04 17:25 UTC, E1-Bart0 commented on Basic collections - string/task_18_6/task_18_6.py
> +    return "".join(chain.from_iterable(encode_text))
Подумай, пожалуйста, как можно без chain сделать)

2022-08-17 15:51 UTC, AlnurT commented on Basic collections - string/task_18_6/task_18_6.py
> +    return "".join(chain.from_iterable(encode_text))
А почему без chain?

2022-10-17 08:24 UTC, merged