Task 19.2
AlnurT/Skillbox_tasks pull request #38
Opened 2022-05-31 09:32 UTC by AlnurT

2022-07-01 06:01 UTC, E1-Bart0 requested changes

2022-07-01 06:01 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_2/task_19_2.py
> +def create_dict_of_counry(country_dict: dict, country: list) -> dict:
Мы как-то не обсуждали, май бад. Но посмотри что значит в Питоне в название чего-то:
`_` нижнее подчеркивание. И давая обсудим, как ты это понимаешь)

2022-07-01 06:01 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_2/test_task_19_2.py
> +}
В фиктуру оберни пожалуйста)

2022-07-01 17:14 UTC, AlnurT commented on Basic collections - Dictionaries and Sets/task_19_2/task_19_2.py
> +    return ""
Хотя нет, тут же страны в множестве сидят, поэтому сложность N

2022-08-19 09:34 UTC, AlnurT commented on Basic collections - Dictionaries and Sets/task_19_2/task_19_2.py
> +def create_dict_of_counry(country_dict: dict, country: list) -> dict:
1) Как я делал, отделение слов.
2) Последнее значение в интерпретаторе.
3) Игнорирование значений, что я юзал в for.
4) Для удобной записи больших чисел.
5) _ в начале названия позволяет использовать переменную и т.д. только внутри. При импорте всего модуля, например, она импортируется. Но при импорте всех элементов модуля, не импортируется.
6) __ в начале используется для искажения имени в классе для исключения конфликтов наименований.
7) _ в конце используется для избегания сходства со встроенными командами.
8) __ с двух сторон имеют специальные переменные.

2022-10-17 08:24 UTC, merged