Task 19.4
AlnurT/Skillbox_tasks pull request #39
Opened 2022-05-31 09:40 UTC by AlnurT

2022-07-01 06:09 UTC, E1-Bart0 requested changes

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/task_19_4.py
> +        total_price = calculate_the_quantity_and_cost_of_goods(store, goods[product])[1]
Объясни, что происходит тут !!!

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/task_19_4.py
> +
Можешь если хочешь попробовать решить как тут
[https://www.youtube.com/watch?v=k2ZWyHdahEk&ab_channel=mCoding](url)

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/task_19_4.py
> +goods = {
В SCREAM_SNAKE_CASE

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/task_19_4.py
> +store = {
S_S_C

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/test_task_19_4.py
> +from task_19_4.task_19_4 import calculate_the_quantity_and_cost_of_goods
Как-то тест не прям правильный. Ты игнорируешь, то что было в main. В прошлых заданиях у тебя обычно в main было взаимодействие с пользователем, а тут ты тестируешь часть фунционала

2022-07-01 06:09 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_4/test_task_19_4.py
> +}
в фикстуру

2022-08-19 10:23 UTC, AlnurT commented on Basic collections - Dictionaries and Sets/task_19_4/task_19_4.py
> +        total_price = calculate_the_quantity_and_cost_of_goods(store, goods[product])[1]
Функция вычисляет количество товара и всю его стоимость. Так делать нельзя, каждая функция должна выполнять свою задачу.

2022-10-17 08:24 UTC, merged