Task 19.8
AlnurT/Skillbox_tasks pull request #42
Opened 2022-05-31 09:59 UTC by AlnurT

2022-07-05 12:45 UTC, E1-Bart0 requested changes

2022-07-05 12:45 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_8/task_19_8.py
> +) -> str:
Лучше чтобы bool возвращало, а за ДА/НЕТ пуская уже другая часть отвечате (отдадим ответсвенность)

2022-07-05 12:45 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_8/test_task_19_8.py
> +    assert is_number_in_possible_numbers({1, 2, 3, 4}, possible_numbers, 3) == answer
Разве мы все проверили, что происходит в этой функии?

2022-08-19 14:40 UTC, AlnurT commented on Basic collections - Dictionaries and Sets/task_19_8/test_task_19_8.py
> +    assert is_number_in_possible_numbers({1, 2, 3, 4}, possible_numbers, 3) == answer
Функция ищет пересечение множеств, редактирует множество чисел и выдает ответ

2022-10-17 08:24 UTC, merged