Task 19.9
AlnurT/Skillbox_tasks pull request #43
Opened 2022-05-31 09:59 UTC by AlnurT

2022-07-05 14:45 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_9/task_19_9.py
> +"""Задача 9. Родословная
Если будут сложность, давай вместе разбираться)

2022-07-05 14:46 UTC, E1-Bart0 requested changes

2022-07-05 14:46 UTC, E1-Bart0 commented on Basic collections - Dictionaries and Sets/task_19_9/task_19_9.py
> +"""Задача 9. Родословная
Ну если есть вопросы пиши, будем вместе разбираться)

2022-08-24 16:31 UTC, AlnurT commented on Basic collections - Dictionaries and Sets/task_19_9/task_19_9.py
> +"""Задача 9. Родословная
Это была самая сложная задача на моей памяти, 3 дня её решал :(

2022-10-17 08:23 UTC, merged