Task 20.9
AlnurT/Skillbox_tasks pull request #49
Opened 2022-06-05 17:28 UTC by AlnurT

2022-07-05 14:42 UTC, E1-Bart0 requested changes

2022-07-05 14:42 UTC, E1-Bart0 commented on Basic collections - Tuples/Task_20_9/task_20_9.py
> +    results_dict = {}
Старайся декларировать такие сложные структуры, чтобы было более понятнее и тебе в будущем и другим:

```
# GLOBAL VARS
Name = str
Score = int
Entry = int
DB = dict[Name, tuple[Name, Score]]

# Local
result_dict: DB = {}
```

2022-08-27 08:55 UTC, AlnurT commented on Basic collections - Tuples/Task_20_9/task_20_9.py
> +        ):
Принято!)

2022-08-27 09:07 UTC, AlnurT commented on Basic collections - Tuples/Task_20_9/task_20_9.py
> +    results_dict = {}
А это нужно прописывать до или после основного тела программы?

2022-10-17 08:23 UTC, merged