Task 16.7
AlnurT/Skillbox_tasks pull request #8
Opened 2022-05-23 18:06 UTC by AlnurT

2022-06-15 09:00 UTC, E1-Bart0 requested changes

2022-06-15 09:00 UTC, E1-Bart0 commented on Methods for working with lists/task_16_7/test_task_16_7.py
> +import pytest
Вот тут ты и попался!

Напиши еще один тест точно такойже, только переименнуй и запусти 2 теста сразу
 pytest test_task_16_7.py

2022-06-15 14:15 UTC, E1-Bart0 commented on Methods for working with lists/task_16_7/test_task_16_7.py
> +import pytest
объясни почему не проходит, попробуй найти решение, если что пиши)

2022-06-30 10:40 UTC, AlnurT commented on Methods for working with lists/task_16_7/test_task_16_7.py
> +import pytest
Не проходит, т.к. словарь изменяется в  первом тесте и во второй приходит уже изменённый

2022-06-30 13:30 UTC, E1-Bart0 requested changes

2022-06-30 13:30 UTC, E1-Bart0 commented on Methods for working with lists/task_16_7/test_task_16_7.py
> +import pytest
Ну вот запомни этот случай и никогда так не делай))
Используй фикстуры для этого

@pytest.fixture()
def data():
    return {'info'}

def test_(data: set) -> None:
    assert data == {'info'}

2022-07-04 17:02 UTC, E1-Bart0 requested changes

2022-07-04 17:02 UTC, E1-Bart0 commented on Methods for working with lists/task_16_7/task_16_7.py
> +    return 0
Я не очень понимаю, типо если у меня 17 размер ноги я могу надеть лапти 47? Давай просто если у меня 42 то я только 42 возьму

2022-07-06 14:54 UTC, AlnurT commented on Methods for working with lists/task_16_7/task_16_7.py
> +    return 0
Да, там в задании было, что можно надеть любой размер, не меньше своего. Исправлю на равный размер.

2022-10-17 08:22 UTC, merged